name: PlatformIO CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [examples/ESP32-CoT-switch_light/ESP32-CoT-switch_light.ino, examples/ESP32-CoT-write_temp_and_hum/ESP32-CoT-write_temp_and_hum.ino]

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        pio pkg install -g -l "adafruit/DHT sensor library@^1.4.3" -l "adafruit/Adafruit Unified Sensor@^1.1.5"
    - name: Run PlatformIO
      run: pio ci --lib="." --board=esp32dev -O "lib_ldf_mode = chain+" -O "lib_deps = Adafruit Unified Sensor"
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
